"""Enumerations used by the domain and application layers."""

from __future__ import annotations

from enum import Enum


class InputMode(str, Enum):
    """Supported ways to define the geographic area."""

    VISUAL_MAP = "VISUAL_MAP"
    AREA_NAME = "AREA_NAME"
    BOUNDING_BOX = "BOUNDING_BOX"


class LargeAreaMode(str, Enum):
    """How generation handles a selection that exceeds one safe voxel budget."""

    BLOCK = "BLOCK"
    SPLIT_TILES = "SPLIT_TILES"


class GeometryType(str, Enum):
    """Geometry families understood by the voxelizer."""

    POINT = "POINT"
    LINE = "LINE"
    POLYGON = "POLYGON"


class FeatureType(str, Enum):
    """Semantic feature categories generated by the add-on."""

    TERRAIN = "Terrain"
    WATER = "Water"
    GREEN = "Green"
    ROAD = "Roads"
    BRIDGE = "Bridges"
    BUILDING = "Buildings"
    TREE = "Trees"


class BuildingSource(str, Enum):
    """Building footprint source selected by the user."""

    OSM_ONLY = "OSM_ONLY"
    OVERTURE_ONLY = "OVERTURE_ONLY"
    HYBRID = "HYBRID"


class HeightSource(str, Enum):
    """Quality/origin of the height assigned to one building feature."""

    REAL_HEIGHT = "REAL_HEIGHT"
    REAL_LEVELS = "REAL_LEVELS"
    BUILDING_PART = "BUILDING_PART"
    INFERRED = "INFERRED"
    DEFAULT = "DEFAULT"


class FootprintSource(str, Enum):
    """Provenance quality of one building footprint."""

    OSM_SURVEYED = "OSM_SURVEYED"
    OVERTURE_CONFLATED = "OVERTURE_CONFLATED"
    MACHINE_EXTRACTED = "MACHINE_EXTRACTED"
    LANDMARK_PROXY = "LANDMARK_PROXY"
    APPROXIMATE = "APPROXIMATE"
    UNKNOWN = "UNKNOWN"


class RoofSource(str, Enum):
    """Origin of the roof geometry assigned to a building."""

    SOURCE_TAG = "SOURCE_TAG"
    SOURCE_HEIGHT = "SOURCE_HEIGHT"
    INFERRED = "INFERRED"
    FLAT_DEFAULT = "FLAT_DEFAULT"


class FacadeSource(str, Enum):
    """Origin of facade colour/material information."""

    SOURCE_MATERIAL = "SOURCE_MATERIAL"
    SOURCE_COLOR = "SOURCE_COLOR"
    NO_SOURCE_DATA = "NO_SOURCE_DATA"
    PROCEDURAL_PROFILE = "PROCEDURAL_PROFILE"
    SIMPLE_CATEGORY = "SIMPLE_CATEGORY"


class AccuracyConfidence(str, Enum):
    """Overall confidence level for one generated building."""

    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    VERY_LOW = "VERY_LOW"


class QualityPreset(str, Enum):
    """Simple generation presets exposed in the primary interface."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CUSTOM = "CUSTOM"


class GeometryStyle(str, Enum):
    """Low-level geometry capabilities used by the generation pipeline."""

    VOXEL_ONLY = "VOXEL_ONLY"
    VOXEL_CURVED = "VOXEL_CURVED"


class ModelStyle(str, Enum):
    """High-level visual styles exposed by the guided setup wizard."""

    CLASSIC_VOXEL = "CLASSIC_VOXEL"
    MINECRAFT = "MINECRAFT"
    LOW_POLY = "LOW_POLY"
    REAL = "REAL"
    ARCHITECTURAL_MODEL = "ARCHITECTURAL_MODEL"


class MaterialStyle(str, Enum):
    """Simple or procedural PBR material system."""

    SIMPLE = "SIMPLE"
    REALISTIC = "REALISTIC"


class LabelMode(str, Enum):
    """Optional map-label generation modes."""

    METADATA_ONLY = "METADATA_ONLY"
    BLENDER_TEXT = "BLENDER_TEXT"


class LabelLanguage(str, Enum):
    """Preferred language order for optional labels."""

    LOCAL = "LOCAL"
    ARABIC = "ARABIC"
    ENGLISH = "ENGLISH"
    BILINGUAL = "BILINGUAL"


class LabelKind(str, Enum):
    """Semantic label categories."""

    AREA = "AREA"
    STREET = "STREET"
    LANDMARK = "LANDMARK"


class CurvedDetailKind(str, Enum):
    """Supported non-voxel detail primitives."""

    DOME = "DOME"
    MINARET = "MINARET"
    TOWER = "TOWER"
    WATER_TOWER = "WATER_TOWER"


class ExportFormat(str, Enum):
    """Model formats available through the simplified exporter."""

    GLB = "GLB"
    FBX = "FBX"
    OBJ = "OBJ"
    USD = "USD"
    BLEND = "BLEND"


class GenerationStage(str, Enum):
    """High-level stages reported to Blender's progress UI."""

    VALIDATING = "Validating input"
    GEOCODING = "Resolving area name"
    DOWNLOADING = "Downloading OpenStreetMap and building data"
    VOXELIZING = "Voxelizing geographic features"
    MESHING = "Building optimized chunk meshes"
    DETAILS = "Building optional visual details"
    FINALIZING = "Finalizing Blender scene"
